FLUTTER=fvm flutter

run:
	$(FLUTTER) run
runp:
	$(FLUTTER) run --release	

build:
	$(FLUTTER) build apk --debug 

buildr:
	$(FLUTTER) build apk --release

build-aab:
	$(FLUTTER) build appbundle --release

.PHONY: run build buildr build-aab runp
